title: Joe Ton # your name (or website title) here
logo: "/images/logo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  My name is Joe, I am a data analyst with experience using various data tools to clean, analyze, and visualize data to empower decision-making and drive changes. I am proficient in SQL, Excel, Power BI, and Python, and I have a good understanding of data analytics techniques including, but not limited to, data preparation, data wrangling, statistical analysis, chart design, dashboard building, process documenting, and data storytelling. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
